name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger this workflow only on push to the main branch

env:
  EKS_CLUSTER_NAME: task-cluster  # Name of your EKS cluster
  AWS_REGION: us-east-1           # AWS region where the cluster is deployed
  IMAGE_NAME: mdr394/task         # Docker image name to be built and pushed

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner to run the CI/CD job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Clones the repository code into the GitHub runner

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access key stored in GitHub secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret key stored in GitHub secrets
        aws-region: ${{ env.AWS_REGION }}  # Region from env variable
      # This step sets up AWS credentials so CLI commands like eks, s3, etc. can run securely

    - name: Authenticate kubectl with EKS
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      # Configures kubectl to connect with the correct EKS cluster context

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # Logs into Docker Hub using secrets to allow pushing images

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:latest .
      # Builds the Docker image from the Dockerfile in the repo root and tags it as "latest"

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest
      # Pushes the tagged image to your Docker Hub repository

    - name: Set up Helm
      uses: azure/setup-helm@v3
      # Installs Helm CLI in the GitHub runner environment

    - name: Deploy using Helm
      run: |
        helm upgrade --install nextjs-app ./helm/nextjs-chart \
          --set image.repository=$IMAGE_NAME \
          --set image.tag=latest
      # Uses Helm to upgrade or install the Kubernetes deployment using the chart in ./helm/nextjs-chart
      # It dynamically sets the image name and tag during the deployment
