name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

env:
  EKS_CLUSTER_NAME: task-cluster
  AWS_REGION: us-east-1
  IMAGE_NAME: mdr394/task

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Authenticate kubectl with EKS
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy using Helm
      run: |
        helm upgrade --install nextjs-app ./helm/nextjs-chart \
          --set image.repository=$IMAGE_NAME \
          --set image.tag=latest
